// eslint-disable-next-line import/extensions
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import { useState } from 'react';
import { Login } from '../components/Login';
import { AnalyticsForm } from '../components/AnalyticsForm';
import { AnalyticsModel } from '../models/responseModels';
import { AnalyticsCharts } from '../components/AnalyticsCharts';

export default function Home() {
  const { data: session } = useSession();
  const [analytics, setAnalytics] = useState<AnalyticsModel>();

  return (
    <>
      <Head>
        <title>K-Analytics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header>
          <Login />
        </header>
        {session && <AnalyticsForm setAnalytics={setAnalytics} />}
        {analytics && <AnalyticsCharts analytics={analytics} />}
      </div>
    </>
  );
}
